### ISSUE TITLE
[FEATURE REQUEST] Managed Identity dev experience improvements

### ISSUE THREAD

**Issue by scottaddie** [microsoft/mssql-jdbc#1930]
As discussed with @David-Engel in an Oct. 3rd meeting, leverage the Azure Identity library to address the following items:

- [ ] Replace Managed Identity token caching logic introduced in https://github.com/microsoft/mssql-jdbc/pull/1825. The Azure Identity library's 1.7.0 release, expected to GA in November, already supports in-memory caching via MSAL in the `ManagedIdentityCredential`. See https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#170-beta1-2022-09-20.
- [ ] Expand the number of supported Azure compute services by relying on the Azure Identity library. For the list the Azure Identity library supports, see https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity/azure-identity#managed-identity-support. Related to https://github.com/microsoft/mssql-jdbc/issues/1844.
- [ ] Improve the local dev experience by supporting both `DefaultAzureCredential` (related to https://github.com/microsoft/mssql-jdbc/issues/1881) and `IntelliJCredential` from the Azure Identity library.

**Comment by g2vinay** [comment]
When Replace Managed Identity token caching logic, following needs to be taken care of:

1. The logic of Token TTL to refresh tokens needs to be retained when using Managed Identity credential directly.
2. When working with Managed Identity credential, for each cache key combination a new instance of Managed Identity Credential will be required.
